### ISSUE TITLE
RE2 Randomizer impossible seed due to spare key being required when it thinks it's not

### ISSUE THREAD

**Issue by lordhelldana** [FuzzyGamesOn/RE2R_AP_Client#32]
Within the Playthrough, the seed expects me to access locker 208 in the safety deposit room for the lion medallion, and this is impossible without the spare key, which one of them is located in the break room after the goddess statue that you need the medallions for.
And the other one is in the interrogation room.

I cannot find where the heart key is in the spoiler log, nor does the playthrough section ever say that it visits these two rooms to collect the spare key needed for the locker room.

I have included the generated world for testing in case you need it.
[AP_67057582508264693689.zip](https://github.com/user-attachments/files/17923198/AP_67057582508264693689.zip)

**Comment by FuzzyGamesOn** [comment]
Hey, thank you for the bug report!

Yeah, we've got a bug in the most recent release where certain lockers aren't respecting the Spare Key requirement. Should be getting a small release out this weekend or soon after to resolve. :smile: 

For now, as a workaround, I've been recommending that people use `start_inventory` in the YAML to start with two Spare Keys, like this:
```
start_inventory:
    { Spare Key: 2 }
```

**Comment by FuzzyGamesOn** [comment]
This is fixed as of today's release, so the above workaround is no longer needed.

Closing this issue but, if you run into any bugs, feel free to open another issue. :smiley:
