### ISSUE TITLE
Softlock Hiding Place Drawer Press room Leon B

### ISSUE THREAD

**Issue by lordhelldana** [FuzzyGamesOn/RE2R_AP_Client#34]
The hiding place drawer in the press room has the 'Film - Hiding Place' marked as a required item according to the location logic, but the drawer does not unlock until you use the film in the dark room.
This makes it possible to soft-lock in the Leon B scenario if the hallway fuse is in this drawer.

**Comment by FuzzyGamesOn** [comment]
This is fixed as of today's release.

Closing this issue but, if you run into any bugs, feel free to open another issue. 😃
